//! PATH-shim routing: generated bash shims that route `npm`, `npx`, `pnpm`,
//! `yarn`, `bun`, `bunx`, `pip`, `cargo`, `yay`, and `paru` invocations
//! through `blueline agent gate` before the real package manager runs. Fail closed everywhere: if
//! blueline is missing, errors, or refuses, the install does not run.
//! Shims are a backstop for the interactive terminal, never the primary
//! gate (hooks and MCP are); every known bypass is documented in the
//! README.

use std::path::{Path, PathBuf};

pub const SHIM_MANAGERS: [&str; 11] = [
    "npm", "npx", "pnpm", "yarn", "bun", "bunx", "pip", "pip3", "cargo", "yay", "paru",
];

fn default_dir() -> anyhow::Result<PathBuf> {
    if let Ok(dir) = std::env::var("BLUELINE_DATA_DIR") {
        return Ok(Path::new(&dir).join("shims"));
    }
    let base = dirs::data_dir()
        .ok_or_else(|| anyhow::anyhow!("could not determine the platform data directory"))?;
    Ok(base.join("blueline").join("shims"))
}

/// Locate the real package-manager binary on PATH, skipping the shim
/// directory so a shim never delegates to another shim (or to itself).
fn find_on_path(name: &str, exclude_dir: &Path) -> anyhow::Result<PathBuf> {
    let path = std::env::var_os("PATH").ok_or_else(|| anyhow::anyhow!("PATH is not set"))?;
    for dir in std::env::split_paths(&path) {
        if dir == exclude_dir {
            continue;
        }
        let candidate = dir.join(name);
        if is_executable_file(&candidate) {
            return Ok(candidate);
        }
    }
    Err(anyhow::anyhow!(
        "no real `{name}` binary found on PATH (excluding the shim directory); \
         refusing to write a shim that cannot exec anything"
    ))
}

fn is_executable_file(path: &Path) -> bool {
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        path.is_file()
            && std::fs::metadata(path)
                .map(|m| m.permissions().mode() & 0o111 != 0)
                .unwrap_or(false)
    }
    #[cfg(not(unix))]
    {
        path.is_file()
    }
}

/// Baked paths land inside double-quoted bash assignments; a path carrying
/// `"`, `$`, a backtick, or a backslash could break out of the assignment
/// and execute arbitrary code at every shim call. Refuse instead of escaping.
fn assert_bakeable(path: &Path, what: &str) -> anyhow::Result<()> {
    let text = path.display().to_string();
    if text.chars().any(|c| matches!(c, '"' | '$' | '`' | '\\')) {
        anyhow::bail!(
            "{what} path `{text}` contains characters that cannot be baked into a shim safely"
        );
    }
    Ok(())
}

fn shim_script(manager: &str, blueline: &Path, real: &Path) -> String {
    let mut script = format!(
        r#"#!/usr/bin/env bash
# Generated by `blueline shim install` for {manager}.
# Fail closed: if blueline is missing, errors, or refuses, the real
# {manager} does not run. Override points: BLUELINE_REGISTRY,
# BLUELINE_POLICY.
BLUELINE="{blueline}"
REAL="{real}"

cmd=("{manager}")
for a in "$@"; do
  cmd+=("$(printf '%q' "$a")")
done
"#,
        blueline = blueline.display(),
        real = real.display(),
    );
    if manager == "pip" || manager == "pip3" {
        script.push_str(
            r#"
# pip flags that name non-registry sources (-r, -e, --constraint, ...) are
# not statically reviewable here; refuse instead of guessing.
if [ "${1:-}" = "install" ] || [ "${1:-}" = "i" ]; then
  for a in "$@"; do
    case "$a" in
      -*) case "$a" in
            -q|--quiet) ;;
            *) echo "blueline shim: pip flag '$a' names or configures non-registry sources; run 'blueline ci --lockfile <requirements>' instead" >&2; exit 2 ;;
          esac ;;
    esac
  done
fi
"#,
        );
    }
    script.push_str(&match manager {
        "npm" | "npx" | "pnpm" | "yarn" | "bun" | "bunx" => r#"
args=(agent gate --command "${cmd[*]}" --format plain)
args+=(--registry "${BLUELINE_REGISTRY:-https://registry.npmjs.org}")
"#
        .to_string(),
        "cargo" => r#"
args=(agent gate --command "${cmd[*]}" --format plain)
args+=(--index "${BLUELINE_INDEX:-https://index.crates.io}")
"#
        .to_string(),
        _ => r#"
args=(agent gate --command "${cmd[*]}" --format plain)
"#
        .to_string(),
    });
    script.push_str(
        r#"
if [ -n "${BLUELINE_POLICY:-}" ]; then
  args+=(--policy "$BLUELINE_POLICY")
fi

"$BLUELINE" "${args[@]}"
rc=$?
if [ "$rc" -ne 0 ]; then
  echo "blueline shim: install blocked by review policy (exit $rc)" >&2
  exit "$rc"
fi

exec "$REAL" "$@"
"#,
    );
    script
}

pub fn install(managers: &[String], dir: Option<&Path>) -> anyhow::Result<()> {
    let dir = match dir {
        Some(d) => d.to_path_buf(),
        None => default_dir()?,
    };
    std::fs::create_dir_all(&dir)
        .map_err(|e| anyhow::anyhow!("creating shim dir {}: {e}", dir.display()))?;
    let blueline = std::env::current_exe()?;
    assert_bakeable(&blueline, "blueline binary")?;
    for manager in managers {
        if !SHIM_MANAGERS.contains(&manager.as_str()) {
            anyhow::bail!(
                "unknown shim manager `{manager}`; known: {}",
                SHIM_MANAGERS.join(", ")
            );
        }
        let real = find_on_path(manager, &dir)?;
        assert_bakeable(&real, "package-manager")?;
        let script = shim_script(manager, &blueline, &real);
        let path = dir.join(manager);
        std::fs::write(&path, script)
            .map_err(|e| anyhow::anyhow!("writing shim {}: {e}", path.display()))?;
        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            std::fs::set_permissions(&path, std::fs::Permissions::from_mode(0o755))
                .map_err(|e| anyhow::anyhow!("chmod {}: {e}", path.display()))?;
        }
        println!(
            "installed {manager} shim: {} (real: {})",
            path.display(),
            real.display()
        );
    }
    println!(
        "add the shim directory to PATH ahead of the real package managers:\n  export PATH=\"{}:$PATH\"",
        dir.display()
    );
    Ok(())
}

pub fn uninstall(managers: &[String], dir: Option<&Path>) -> anyhow::Result<()> {
    let dir = match dir {
        Some(d) => d.to_path_buf(),
        None => default_dir()?,
    };
    for manager in managers {
        if !SHIM_MANAGERS.contains(&manager.as_str()) {
            anyhow::bail!(
                "unknown shim manager `{manager}`; known: {}",
                SHIM_MANAGERS.join(", ")
            );
        }
        let path = dir.join(manager);
        match std::fs::remove_file(&path) {
            Ok(()) => println!("removed {manager} shim: {}", path.display()),
            Err(e) if e.kind() == std::io::ErrorKind::NotFound => {
                println!("no {manager} shim at {}", path.display());
            }
            Err(e) => {
                return Err(anyhow::anyhow!("removing shim {}: {e}", path.display()));
            }
        }
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn all_shim_managers_cover_every_scanned_manager() {
        for manager in [
            "npm", "npx", "pnpm", "yarn", "bun", "bunx", "pip", "pip3", "cargo", "yay", "paru",
        ] {
            assert!(
                SHIM_MANAGERS.contains(&manager),
                "scanned manager `{manager}` must have shim coverage"
            );
        }
    }

    #[test]
    fn node_family_shims_forward_the_registry_override() {
        for manager in ["pnpm", "yarn", "bun", "bunx"] {
            let script = shim_script(
                manager,
                Path::new("/usr/local/bin/blueline"),
                Path::new("/usr/bin/tool"),
            );
            assert!(
                script.contains("BLUELINE_REGISTRY"),
                "{manager} shim must forward BLUELINE_REGISTRY"
            );
            assert!(script.contains("agent gate"));
            assert!(script.contains("exec \"$REAL\" \"$@\""));
        }
    }

    #[test]
    fn shim_script_is_fail_closed_and_execs_real_binary() {
        let script = shim_script(
            "npm",
            Path::new("/usr/local/bin/blueline"),
            Path::new("/usr/bin/npm"),
        );
        assert!(script.contains("BLUELINE=\"/usr/local/bin/blueline\""));
        assert!(script.contains("REAL=\"/usr/bin/npm\""));
        assert!(script.contains("agent gate"));
        assert!(script.contains("exec \"$REAL\" \"$@\""));
        assert!(script.contains("exit \"$rc\""));
        assert!(!script.contains("pip flag"));
    }

    #[test]
    fn pip_shim_refuses_non_registry_flags() {
        let script = shim_script("pip", Path::new("/bin/blueline"), Path::new("/usr/bin/pip"));
        assert!(script.contains("pip flag"));
        assert!(script.contains("blueline ci"));
        let npm = shim_script("npm", Path::new("/bin/blueline"), Path::new("/usr/bin/npm"));
        assert!(!npm.contains("pip flag"));
    }

    #[test]
    fn find_on_path_skips_the_shim_directory() {
        let dir = tempfile::tempdir().unwrap();
        let real_dir = tempfile::tempdir().unwrap();
        let fake = real_dir.path().join("npm");
        std::fs::write(&fake, "#!/bin/sh\nexit 0\n").unwrap();
        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            std::fs::set_permissions(&fake, std::fs::Permissions::from_mode(0o755)).unwrap();
        }
        let joined = std::env::join_paths([
            dir.path(),
            real_dir.path(),
            std::path::Path::new("/nonexistent"),
        ])
        .unwrap();
        let found = find_on_path_with("npm", dir.path(), &joined).unwrap();
        assert_eq!(found, fake);
        let only_shim_dir = std::env::join_paths([dir.path()]).unwrap();
        assert!(find_on_path_with("npm", dir.path(), &only_shim_dir).is_err());
    }

    #[test]
    fn default_dir_resolves_under_data_dir() {
        let dir = default_dir().expect("data dir must resolve");
        assert!(!dir.as_os_str().is_empty());
        assert!(
            dir.ends_with("shims"),
            "resolved shim dir must end with shims: {}",
            dir.display()
        );
    }

    #[test]
    fn executable_check_requires_file_and_exec_bit() {
        assert!(!is_executable_file(Path::new(
            "/nonexistent-blueline-shim-probe"
        )));
        let dir = tempfile::tempdir().unwrap();
        let plain = dir.path().join("tool");
        std::fs::write(&plain, "#!/bin/sh\nexit 0\n").unwrap();
        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            std::fs::set_permissions(&plain, std::fs::Permissions::from_mode(0o644)).unwrap();
        }
        assert!(!is_executable_file(&plain));
        assert!(!is_executable_file(Path::new(
            "/nonexistent-blueline-shim-probe"
        )));
    }

    #[test]
    fn executable_check_accepts_755() {
        let dir = tempfile::tempdir().unwrap();
        let exe = dir.path().join("tool");
        std::fs::write(&exe, "#!/bin/sh\nexit 0\n").unwrap();
        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            std::fs::set_permissions(&exe, std::fs::Permissions::from_mode(0o755)).unwrap();
        }
        assert!(is_executable_file(&exe));
    }

    #[test]
    fn bakeable_rejects_shell_metacharacters() {
        assert!(assert_bakeable(Path::new("/opt/blueline/bin"), "blueline binary").is_ok());
        for dangerous in [
            "/tmp/$HOME/blueline",
            "/tmp/`evil`/blueline",
            "/tmp/\"quoted\"/blueline",
            "/tmp/back\\slash/blueline",
        ] {
            assert!(
                assert_bakeable(Path::new(dangerous), "blueline binary").is_err(),
                "{dangerous} must not bake"
            );
        }
    }

    #[test]
    fn cargo_shim_resolves_the_cargo_real_binary() {
        let script = shim_script(
            "cargo",
            Path::new("/usr/local/bin/blueline"),
            Path::new("/usr/bin/cargo"),
        );
        assert!(script.contains("cargo"));
        assert!(
            script.contains("BLUELINE_INDEX"),
            "cargo shim must resolve the real cargo binary via the index override"
        );
        assert!(script.contains("index.crates.io"));
        let generic = shim_script(
            "yay",
            Path::new("/usr/local/bin/blueline"),
            Path::new("/usr/bin/yay"),
        );
        assert!(!generic.contains("BLUELINE_INDEX"));
    }

    #[test]
    fn uninstalling_an_absent_shim_succeeds() {
        let dir = tempfile::tempdir().unwrap();
        uninstall(&["npm".to_string()], Some(dir.path())).expect("absent shim must succeed");
    }

    #[test]
    fn uninstall_propagates_non_notfound_errors() {
        let dir = tempfile::tempdir().unwrap();
        let blocking = dir.path().join("npm");
        std::fs::create_dir(&blocking).unwrap();
        let err = uninstall(&["npm".to_string()], Some(dir.path()))
            .expect_err("non-NotFound IO errors must propagate");
        assert!(format!("{err:#}").contains("removing shim"));
    }

    fn find_on_path_with(
        name: &str,
        exclude_dir: &Path,
        path_var: &std::ffi::OsStr,
    ) -> anyhow::Result<PathBuf> {
        for dir in std::env::split_paths(path_var) {
            if dir == exclude_dir {
                continue;
            }
            let candidate = dir.join(name);
            if candidate.is_file() {
                return Ok(candidate);
            }
        }
        Err(anyhow::anyhow!("no real `{name}` binary found on PATH"))
    }
}
